In [41]:
import numpy as np

N,M = map(int, raw_input().split())
# numpy eye function
print np.eye(N, M)

6 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [40]:
# looping
for i in range(N):
    for j in range(M):
        if i == j:
            print '1 ',
            continue
        print '0 ',
    print ''
        

1  0  0  0  0  0  
0  1  0  0  0  0  
0  0  1  0  0  0  
0  0  0  1  0  0  
0  0  0  0  1  0  
